apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxcro-user-info-deployment
  labels:
    app: mxcro
    microservice: user_info
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: mxcro
      microservice: user_info
  template:
    metadata:
      labels:
        app: mxcro
        microservice: user_info
    spec:
      containers:
      - name: mxcro-user-info
        image: jan146/mxcro:1.1
        imagePullPolicy: Always
        command: ["python"]
        args: ["-m", "user_info.src.api.v1.api"]
        ports:
        - containerPort: 5000
          name: flask
        envFrom:
          - configMapRef:
              name: mxcro-config-map
          - secretRef:
              name: mxcro-secrets

