apiVersion: v1
kind: Service
metadata:
  name: mxcro-user-info-service
spec:
  selector:
    app: mxcro
    microservice: user_info
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

