apiVersion: v1
kind: Service
metadata:
  name: mxcro-user-info-service
spec:
  selector:
    app: mxcro
    microservice: user_info
  ports:
    - port: {{ .Values.portNumber }}
      targetPort: {{ .Values.portNumber }}
  type: {{ .Values.serviceType }}

