apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxcro-food-item-deployment
  labels:
    app: mxcro
    microservice: food_item 
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: mxcro
      microservice: food_item
  template:
    metadata:
      labels:
        app: mxcro
        microservice: food_item 
    spec:
      containers:
      - name: mxcro-food-item
        image: jan146/mxcro:stable
        imagePullPolicy: Always
        command: ["python"]
        args: ["-m", "food_item.src.api.v1.api"]
        ports:
        - name: flask
          containerPort: 5000
        envFrom:
          - configMapRef:
              name: mxcro-config-map
          - secretRef:
              name: mxcro-secrets
        livenessProbe:
          httpGet:
            path: /api/v1/food_item/health/live
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/v1/food_item/health/ready
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3

