apiVersion: v1
kind: Service
metadata:
  name: mxcro-food-item-service
spec:
  selector:
    app: mxcro
    microservice: food_item 
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

