apiVersion: v1
kind: Service
metadata:
  name: mxcro-logged-item-service
spec:
  selector:
    app: mxcro
    microservice: logged_item
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

