apiVersion: v1
kind: Service
metadata:
  name: mxcro-logged-item-service
spec:
  selector:
    app: mxcro
    microservice: logged_item
  ports:
    - port: {{ .Values.portNumber }}
      targetPort: {{ .Values.portNumber }}
  type: {{ .Values.serviceType }}

