apiVersion: v2
name: helm-mxcro-shared
description: A Helm chart for mxcro's shared k8s objects (Ingress & ConfigMap)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mxcro
  - shared
dependencies:
  - name: ingress-nginx
    version: "4.1.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
sources:
  - https://github.com/jan146/mxcro/

