apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-service
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus

