# Default values for helm-mxcro-food-item.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
imageTag: latest
maxUnavailable: 1
maxSurge: 1
portNumber: 5000
serviceType: LoadBalancer

