apiVersion: v1
kind: Service
metadata:
  name: mxcro-food-item-service
spec:
  selector:
    app: mxcro
    microservice: food_item 
  ports:
    - port: {{ .Values.portNumber }}
      targetPort: {{ .Values.portNumber }}
  type: {{ .Values.serviceType }}

