name: Default CI/CD pipeline
run-name: ${{ github.actor }} started workflow ${{ github.workflow }}, with run ID ${{ github.run_id }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:

  test:
    runs-on: ubuntu-latest
    env:
      # Default env vars
      FLASK_DEBUG: True
      FLASK_HOST: 127.0.0.1
      FLASK_PORT: 5000
      ENVIRONMENT: development
      MONGO_DB_NAME: mxcro
      MONGO_DB_TEST: mxcro-test
      MONGO_HOST: 127.0.0.1
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      BACKEND_URL: http://127.0.0.1:5000
      # Secrets
      SERVERLESS_NAMESPACE_URL: ${{ secrets.SERVERLESS_NAMESPACE_URL }}
      CALORIE_NINJAS_API_KEY: ${{ secrets.CALORIE_NINJAS_API_KEY }}
      SERVERLESS_AUTH: ${{ secrets.SERVERLESS_AUTH }}
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "requirements.txt"
      - name: Run food_item unit tests
        run: python -m pytest food_item/test/unit_test.py
      - name: Run user_info unit tests
        run: python -m pytest user_info/test/unit_test.py
      - name: Run integration tests
        run: python -m pytest test/integration_test.py
      - run: echo "Job finished with status ${{ job.status }}."

  publish-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: Containerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/mxcro:build-${{ github.run_id }}
            ${{ vars.DOCKER_USERNAME }}/mxcro:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
     - uses: actions/checkout@v4
     - uses: azure/setup-kubectl@v4
       with:
          version: "latest"
     - uses: azure/setup-helm@v4.2.0
       with:
          version: "latest"
     - run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig
     - env:
         KUBECONFIG: ${{ github.workspace }}/kubeconfig
       run: |
         helm dependency build k8s/helm-mxcro-shared
         helm upgrade --install mxcro-shared k8s/helm-mxcro-shared
         helm upgrade --install mxcro-food-item food_item/helm-mxcro-food-item -f food_item/helm-mxcro-food-item/values.production.yaml
         helm upgrade --install mxcro-logged-item logged_item/helm-mxcro-logged-item -f logged_item/helm-mxcro-logged-item/values.production.yaml
         helm upgrade --install mxcro-user-info user_info/helm-mxcro-user-info -f user_info/helm-mxcro-user-info/values.production.yaml

