name: Default CI/CD pipeline
run-name: ${{ github.actor }} started workflow ${{ github.workflow }}, with run ID ${{ github.run_id }} 
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "requirements.txt"
      - name: Run food_item tests
        run: python -m pytest food_item/test/unit_test.py
      - name: Run user_info tests
        run: python -m pytest user_info/test/unit_test.py
      - run: echo "Job finished with status ${{ job.status }}."

